/**
 * Artifact inventory (T053): Explicit approved file/hash list for ZIP creation.
 * One project root with defined subdirectories and exclusion patterns.
 * No unrestricted workspace walk determines ZIP contents.
 */

/** Approved relative paths that can be included in artifacts */
const APPROVED_ARTIFACT_PATHS: readonly string[] = [
    // Root configuration files
    "package.json",
    "package-lock.json",
    "README.md",
    "tsconfig.json",
    "tsconfig.app.json",
    "tsconfig.spec.json",
    "angular.json",
    ".eslintrc.json",
    "vitest.config.ts",

    // Directories
    "src/",
    "public/",
    "assets/",
    "styles/",
];

/** Path patterns that are explicitly forbidden in artifacts */
const FORBIDDEN_ARTIFACT_PATTERNS: readonly RegExp[] = [
    // Node.js/NPM
    /^node_modules\//,
    /^\.npm/,
    /^npm-debug\.log/,
    /^package-lock\.json$/,  // Don't include original lockfile (will be generated)

    // Build output
    /^dist\//,
    /^build\//,
    /^\.angular\//,
    /^out\//,

    // Cache directories
    /^\.cache\//,
    /^\.next\//,
    /^\.nuxt\//,
    /^\.webpack\//,
    /^tmp\//,
    /^temp\//,

    // Logs
    /\.log$/,
    /^logs\//,

    // VCS metadata
    /^\.git\//,
    /^\.gitignore$/,
    /^\.gitkeep$/,
    /^\.svn\//,
    /^\.hg\//,

    // Environment and secrets
    /^\.env/,
    /^\.env\.local/,
    /^\.env\.*.local/,
    /^secrets\//,
    /^credentials\//,

    // IDE and editor
    /^\.vscode\//,
    /^\.idea\//,
    /^\.DS_Store$/,
    /^Thumbs\.db$/,
    /^\.editorconfig$/,

    // Test coverage and reports
    /^coverage\//,
    /^\.nyc_output\//,
    /^\.junit\//,

    // Temporary files
    /\.swp$/,
    /\.swo$/,
    /\.swn$/,
    /~$/,
    /\.tmp$/,
    /\.bak$/,

    // Ruby/Gemfile artifacts
    /^Gemfile\.lock$/,
    /^vendor\/bundle\//,

    // Python artifacts
    /^__pycache__\//,
    /\.pyc$/,
    /\.pyo$/,
    /^\.venv\//,
    /^venv\//,

    // Docker/container artifacts
    /^\.docker\//,
    /^Dockerfile$/,
    /^docker-compose\.yml$/,

    // CI/CD configuration (don't expose credentials/settings)
    /^\.github\//,
    /^\.gitlab-ci\.yml$/,
    /^\.travis\.yml$/,

    // Generated by TypeScript/Angular
    /\.js\.map$/,
    /\.spec\.js$/,
];

export interface ApprovedFile {
    readonly relativePath: string;
    readonly sha256: string | null;
    readonly bytes: number | null;
}

export interface ArtifactInventory {
    readonly projectRoot: string;
    readonly approvedFiles: readonly ApprovedFile[];
    readonly createdAt: string;
}

/**
 * Validates that a file path is safe to include in an artifact.
 * Returns true if the path can be included; false if forbidden.
 */
export function isPathApprovedForArtifact(relativePath: string): boolean {
    // Normalize path separators to forward slashes
    const normalized = relativePath.replace(/\\/g, "/");

    // Reject absolute paths or path traversal
    if (normalized.startsWith("/") || normalized.includes("../")) {
        return false;
    }

    // Reject if it matches any forbidden pattern
    for (const pattern of FORBIDDEN_ARTIFACT_PATTERNS) {
        if (pattern.test(normalized)) {
            return false;
        }
    }

    // Accept paths that are explicit approvals or under approved directories
    for (const approved of APPROVED_ARTIFACT_PATHS) {
        if (approved.endsWith("/")) {
            // Directory approval
            if (normalized.startsWith(approved)) {
                return true;
            }
        } else {
            // Exact file approval
            if (normalized === approved) {
                return true;
            }
        }
    }

    // Special case: generated reports are always approved
    if (normalized === "migration-report.json" || normalized === "migration-report.md") {
        return true;
    }

    return false;
}

/**
 * Validates the integrity of a file entry against recorded metadata.
 * Returns true if valid; false if corrupted or tampered.
 */
export function validateFileIntegrity(
    relativePath: string,
    actualBytes: number,
    actualSha256: string | null,
    expected: ApprovedFile
): boolean {
    // Path must match exactly
    if (relativePath !== expected.relativePath) {
        return false;
    }

    // Byte length must match if recorded
    if (expected.bytes !== null && actualBytes !== expected.bytes) {
        return false;
    }

    // SHA-256 must match if recorded
    if (expected.sha256 !== null && actualSha256 !== expected.sha256) {
        return false;
    }

    return true;
}

/**
 * Creates an artifact inventory from a list of files.
 * All files must pass isPathApprovedForArtifact check.
 */
export function createArtifactInventory(
    projectRoot: string,
    files: readonly { relativePath: string; sha256: string | null; bytes: number }[]
): ArtifactInventory {
    const approvedFiles: ApprovedFile[] = [];

    for (const file of files) {
        if (!isPathApprovedForArtifact(file.relativePath)) {
            throw new Error(`Path not approved for artifact: ${file.relativePath}`);
        }

        approvedFiles.push({
            relativePath: file.relativePath,
            sha256: file.sha256,
            bytes: file.bytes
        });
    }

    return {
        projectRoot,
        approvedFiles,
        createdAt: new Date().toISOString()
    };
}
